// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDULBqgWdTz0OrKlrLxApnWk3MI2h_--j0',
    appId: '1:622621100205:web:49c15b31e122f1016d1e24',
    messagingSenderId: '622621100205',
    projectId: 'munchify-6cfb1',
    authDomain: 'munchify-6cfb1.firebaseapp.com',
    storageBucket: 'munchify-6cfb1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRzWh56lhOz9CedNXrVdb3f6G0Qf5XR0U',
    appId: '1:622621100205:android:e5845cb283b6104b6d1e24',
    messagingSenderId: '622621100205',
    projectId: 'munchify-6cfb1',
    storageBucket: 'munchify-6cfb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATT1rsOBcoTtNp5yQ2teZ4ac3RbXxUGrE',
    appId: '1:622621100205:ios:02be32d4c66364146d1e24',
    messagingSenderId: '622621100205',
    projectId: 'munchify-6cfb1',
    storageBucket: 'munchify-6cfb1.appspot.com',
    iosBundleId: 'com.example.munchify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATT1rsOBcoTtNp5yQ2teZ4ac3RbXxUGrE',
    appId: '1:622621100205:ios:02be32d4c66364146d1e24',
    messagingSenderId: '622621100205',
    projectId: 'munchify-6cfb1',
    storageBucket: 'munchify-6cfb1.appspot.com',
    iosBundleId: 'com.example.munchify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDULBqgWdTz0OrKlrLxApnWk3MI2h_--j0',
    appId: '1:622621100205:web:97652612aae052406d1e24',
    messagingSenderId: '622621100205',
    projectId: 'munchify-6cfb1',
    authDomain: 'munchify-6cfb1.firebaseapp.com',
    storageBucket: 'munchify-6cfb1.appspot.com',
  );
}
